/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JL;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // String source = String.join(" ",args);
        for (String arg:args) {
            System.out.println(arg);

        }
        System.out.println(new Frame("Hello"));
    }
}
